@startuml
package "CatalogoPlaylist" {

    interface "ComponentePlaylist" {
        +mostrarInformacion(): void
    }

    class "Playlist" implements "ComponentePlaylist" {
        -idPlaylist: int
        -tituloPlaylist: String
        -descripcion: String
        -propietario: Perfil
        -imagenPortada: BufferedImage
        -componentes: List<ComponentePlaylist>

        +Playlist(titulo: String, descripcion: String, propietario: Perfil)
        +getTitulo(): String
        +getDescripcion(): String
        +getPropietario(): Perfil
        +calcularCantidadCanciones(): int

        +mostrarInformacion(): void
        +obtenerDuracion(): double
        +agregar(componente: ComponentePlaylist): void
        +eliminar(componente: ComponentePlaylist): void
        +getComponentes(): List<ComponentePlaylist>
    }

    class "PlaylistDAO" {
        +registrarPlaylist(playlist: Playlist): void
        +actualizarPlaylist(playlist: Playlist): void
        +eliminarPlaylist(playlist: Playlist): void
        +buscarPlaylist(): List<Playlist>
        +buscarPlaylistPorId(id: int): Playlist
        +buscarPlaylistPorNombre(nombre: String): List<Playlist>
        +obtenerPlaylistPorUsuario(usuario: Perfil): List<Playlist>
    }

    class "ServicioValidacionPlaylist" {
        +validarDatosCompletos(playlist: Playlist): boolean
        +tieneDuplicados(playlist: Playlist): boolean
        +validarDescripcion(descripcion: String): boolean
        +validarTitulo(titulo: String): boolean
    }

    PlaylistDAO --> ServicioValidacionPlaylist : usa
    PlaylistDAO --> Playlist : gestiona
    Playlist *-- ComponentePlaylist : contiene
}

package "CatalogoCanciones" {
    class "Cancion" {
        -idCancion: int
        -tituloCancion: String
        -artista: List<Artista>
        -generos: List<Genero>
        -duracion: double
        -anioCancion: int
        -portadaCancion: BufferedImage
        -archivoMP3: BLOB
        -fechaAgregado: Date
        -orden: int

        +getFechaAgregado(): Date
        +getOrden(): int
        +setOrden(orden: int): void
    }
}

Cancion ..|> ComponentePlaylist : implements

@enduml
