@startuml
package "Administración de usuarios" {
  class Perfil {
    - nombre: String
    - apellido: String
    - correo: String
    - contrasenia: String
    - estadoCuenta: String
    - fechaRegistro: Date
    - foto: String
  }

  class Usuario {
    - preferenciasMusicales: List<Genero>
    + actualizarPerfil(nombre, apellido, foto): void
    + agregarPreferenciasMusicales(generos: List<Genero>): void
  }

  class Administrador {
    + consultarUsuarios(): List<Perfil>
    + activarCuenta(usuario: Perfil): void
    + desactivarCuenta(usuario: Perfil): void
    + cambiarTipoUsuario(usuario: Perfil, tipoUsuario: TipoUsuario): void
    + eliminarCuenta(usuario: Perfil): void
  }

  class ServicioPerfil {
    - perfilDTO: PerfilDTO
    - {static} encoder: PasswordEncoder
    + registrarUsuario(nombre, apellido, correo, contrasenia, foto): void
    + autenticar(email, password): Perfil
  }
  Enum Genero
  Enum TipoUsuario {
  ADMINISTRADOR
  USUARIO
  }
  class Sesion {
    - usuarioActual: Perfil
    - {static} sesion: Sesion
    + {static} getSesion(): Sesion
    + iniciarSesio(usarioLogueado: Perfil): void
    + cerrarSesion(): void
    + obtenerUsuarioActual(): Perfil
  }

  ServicioPerfil .> Perfil
  Usuario --|> Perfil
  Administrador --|> Perfil
  Usuario -> "*" Genero : preferenciasMusicales
  Perfil --> "1" TipoUsuario: tipoUsuario
  Sesion --> Perfil

}



@enduml
