@startuml
package "Administración de usuarios" {

  class Perfil {
    - nombre: String
    - apellido: String
    - email: String
    - contrasenia: String
    - estadoCuenta: String
    - fechaRegistro: Date
    - foto: String
  }

  class Usuario {
    - preferenciasMusicales: List<Genero>
    + actualizarPerfil(nombre, apellido, foto): void
    + agregarPreferenciasMusicales(generos: List<Genero>): void
  }

  class Administrador {
    + consultarUsuarios(): List<Perfil>
    + activarCuenta(usuario: Perfil): void
    + desactivarCuenta(usuario: Perfil): void
    + cambiarTipoUsuario(usuario: Perfil, tipoUsuario: TipoUsuario): void
    + eliminarCuenta(usuario: Perfil): void
  }

  class ServicioPerfil {
    - perfilDAO: PerfilDAO
    - {static} encoder: PasswordEncoder
    + registrarUsuario(nombre, apellido, correo, contrasenia, foto): void
    + autenticar(email, password): Perfil
  }
  Enum Genero
  Enum TipoUsuario {
  ADMINISTRADOR
  USUARIO
  }
  class Sesion {
    - {static} usuarioLogueado: Perfil
    + {static} iniciarSesio(usarioLogueado: Perfil): void
    + {static} obtenerUsuarioActual(): Perfil
    + {static} cerrarSesion(): void
  }

  ServicioPerfil .> Perfil
  Usuario --|> Perfil
  Administrador --|> Perfil
  Usuario -> "*" Genero : preferenciasMusicales
  Perfil --> "1" TipoUsuario: tipoUsuario
  ServicioPerfil --> Sesion

}

@enduml
